name: Cleanup Cron Job
on:
  # Run every 5 minutes
  schedule:
    - cron: '*/5 * * * *'
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Run on push to test
  push:
    branches: [ main, master ]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Check current time
        run: echo "🕐 Cron job started at $(date)"
      
      - name: Run Cleanup Script
        run: |
          echo "🔄 Calling cleanup endpoint..."
          
          # Call your InfinityFree cleanup script
          RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}\nTIME:%{time_total}s" \
            "https://1osbr3aker.rf.gd/cron/cleanup.php")
          
          # Extract parts
          BODY=$(echo "$RESPONSE" | grep -v "HTTP_STATUS" | grep -v "TIME" | head -1)
          HTTP_STATUS=$(echo "$RESPONSE" | grep "HTTP_STATUS" | cut -d':' -f2)
          TIME_TAKEN=$(echo "$RESPONSE" | grep "TIME" | cut -d':' -f2)
          
          echo "📊 Response: $BODY"
          echo "📡 HTTP Status: $HTTP_STATUS"
          echo "⏱️ Time taken: ${TIME_TAKEN}s"
          
          # Check if successful
          if [ "$HTTP_STATUS" = "200" ] || [ "$HTTP_STATUS" = "000" ]; then
            echo "✅ Cleanup executed successfully"
          else
            echo "❌ Cleanup failed with HTTP $HTTP_STATUS"
            exit 1
          fi
      
      - name: Verify Cleanup
        run: |
          echo "🔍 Checking if cleanup worked..."
          # Add verification logic if needed
          echo "✅ Cleanup verification complete"
      
      - name: Send Success Notification
        if: success()
        run: |
          echo "🎉 Cron job completed successfully!"
          echo "Next run in 5 minutes"
      
      - name: Send Failure Notification
        if: failure()
        run: |
          echo "❌ Cron job failed!"
          echo "Check the logs above for errors"